---
title: "Untitled"
author: "shirley"
date: "2019年5月29日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)

now2 <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
```

```{r}
x <- now2()
x
```

```{r}
textbookURL <- function(){
  browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/")
}
```

```{r}
demand_supply_fun<- function(P,a,b,c,d){
  Qs <- a+b*P
  Qd <- c-d*P
  return(
    list(供給量=Qs,
        需求量=Qd,
        超額供給量=Qs-Qd))
}

```

```{r}
a <-  readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
} else {
  print("a不為負值")
}
```

```{r}
supply_fun3 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P can't  be negative") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else {
    return(Qs)
  }
}
supply_fun3(P=-1,0,1)
supply_fun3(P=2,0,1)
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`必選修類別（必∕選∕通）`
major <- transcriptDataFinal$學系
studentID <- transcriptDataFinal$學號
grade <- transcriptDataFinal$學期成績
```


```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  if(studentID %in% transcriptDataFinal$學號){
  return(GPA)
  }else{
      message("No such ID")
    }
}

gpa_fun("92aS67fee") 
gpa_fun("aa829838s")
```

```{r}
gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
gpa_fun2("92aS67fee")
```


```{r}
fizzbuzz <- function(number){
  if(number %% 15== 0){
    return("fizzbuzz")}
    else if(number%% 3 ==0){
      return("fizz")
    }else if (number%% 5 == 0){
      return("buzz")
    }else {
      return(number)
    }
  }
```

```{r}
b<- c(5,1,3)
```

#要每個b元素都>2，使用all()
```{r}
if(all(b>2)){
  print("b大於2")
} else{
  print("不是所有的b都大於2")
}

```

#只要其中一個b元素>2，使用any()
```{r}
if(any(b>2)){
  print("b大於2")
}
```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a==1) {
  print("你輸入了1")
} else if(a==2) {
  print("你輸入了2")
} else if(a==3) {
  print("你輸入了3")
} else {
  print("你輸入了其他數字")
}
```

