---
title: "Untitled"
author: "shirley"
date: "2019年6月5日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta
  return(utilValue)
}
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8)
```

```{r}
utility_cobb_douglass(1,2,.beta=0.8,.alpha=0.5)
```

```{r}
utility_cobb_douglass(y=2,x=1,.beta=0.8,.alpha=0.5)
```

```{r}
load(url("https://github.com/tpemartin/github-data/blob/master/loopTranscriptData.Rda?raw=true"))
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```


```{r}
gpa_fun(transcriptDataFinal$學號[[1]])
```

```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

```{r}
for (i in gmailAddress) {
  print(i)
  
}

for(i in c(1:4)){
  print(i)
  print(gmailAddress[[i]])
}

for (i in seq_along(gmailAddress)) {
  print(gmailAddress[[i]])
  
}
```

