---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")

dialogue
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE,T,T)
class(aLogical)
```

```{r}
# 加總向量內的所有元素值。
sum(aLogical)
```

```{r}
birthplace <- factor(
  c("台北市","新北市","台中市")
) 
class(birthplace)
typeof(birthplace)
levels(birthplace)
as.integer(birthplace)
```
```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
typeof(studentMajors)
levels(studentMajors)
studentMajors
as.integer(studentMajors)
```

charater cannot be calculated
```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算

trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
sum(trueInteger)

a <- 5
b <- 6
c <- -11

class(a)
a+b+c


```


```{r}
library(lubridate)
```


```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
dtObject
typeof(dtObject)
as.integer(dtObject)
as.double(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime
as.integer(twDateTime)

LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
as.integer(LisbonDateTime)
```

