---
title: '2019-04-03'
author: "林茂廷"
date: "3/31/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)

aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)

c <- 4

c+a

a^b
a %% b
b %% a
```

```{r}
library(lubridate)
date1 <- ymd("2019-08-11")
date2 <- ymd("2000-02-01")
date1
date2
class(date1)
class(date2)

as.integer(date1)
as.integer(date2)
difference <- date1-date2
difference
class(difference)
```


```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")

x3 == y3
x3 != y3

!(x3 == y3)


x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```

```{r}
currency <- as.factor(currency)
levels(currency)
length(levels(currency))
length(currency)
sum(currency == "日圓JPY/USD")
```

```{r}
x7 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x7 %in% greatTaipei
!(x7 %in% greatTaipei)

greatTaipei %in% x7

x21 <- c(1,NA,10)
y21 <- c(-1,NA,20)

x31 <- c(NA,"小花")
y31 <- c(NA,"小華")

is.na(x21)
```

```{r}
y7 <- c("女","男","女")

y7=="女"
!(y7=="女")
```

```{r}
x7 %in% greatTaipei
y7 =="女"

(x7 %in% greatTaipei) & (y7=="女")
which((x7 %in% greatTaipei) & (y7=="女"))

(x7 %in% greatTaipei) | (y7=="女")
which((x7 %in% greatTaipei) | (y7=="女"))

xor(x7 %in% greatTaipei, y7=="女")
which(xor(x7 %in% greatTaipei, y7=="女"))
```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```

```{r}
class (date)
```

```{r}
library(lubridate)
date <- ymd(date)
```

```{r}
class(date)
```

```{r}
head(as.integer(date))
as.integer(ymd("1980-08-01"))
head(date >= ymd("1980-08-01"))

isAfter19800801 <- date >= ymd("1980-08-01")
sum(isAfter19800801)
```

```{r}
isEURO <- currency == "歐元USD/EUR"
sum(isEURO)
```

```{r}
isexchangerateNA <- is.na(exchangeRate)
sum(isexchangerateNA)
```

```{r}
isNotNA <- !is.na(exchangeRate)
isEURO <- currency == "歐元USD/EUR"

satisgyBoth <- (isNotNA & isEURO)
sum(satisgyBoth)
```

